--
-- PostgreSQL database dump
--

-- Dumped from database version 10.14
-- Dumped by pg_dump version 10.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: auspiciador; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auspiciador (
    id bigint NOT NULL,
    contacto character varying(255),
    create_at timestamp without time zone,
    descripcion character varying(255),
    link character varying(255),
    logo character varying(255),
    nombre character varying(255),
    gestion_id bigint
);


ALTER TABLE public.auspiciador OWNER TO postgres;

--
-- Name: auspiciador_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auspiciador ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auspiciador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equipo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.equipo (
    id_equipo bigint NOT NULL,
    create_at timestamp without time zone,
    habilitado boolean NOT NULL,
    nombre character varying(255),
    encargado_cod_registro character varying(255),
    tipo_equipo_id bigint
);


ALTER TABLE public.equipo OWNER TO postgres;

--
-- Name: equipo_id_equipo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.equipo ALTER COLUMN id_equipo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipo_id_equipo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gestion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gestion (
    id bigint NOT NULL,
    descripcion character varying(255),
    fecha_fin date,
    fecha_ini date,
    gestion character varying(255),
    periodo character varying(255)
);


ALTER TABLE public.gestion OWNER TO postgres;

--
-- Name: gestion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gestion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gestion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jurado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jurado (
    id bigint NOT NULL,
    created_at timestamp without time zone,
    grado_academico character varying(255),
    telefono character varying(255),
    usuario_cod_registro character varying(255)
);


ALTER TABLE public.jurado OWNER TO postgres;

--
-- Name: jurado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.jurado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jurado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jurado_proyectos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jurado_proyectos (
    id bigint NOT NULL,
    create_at timestamp without time zone,
    funcionalidad double precision,
    impacto double precision,
    innovacion double precision,
    presentacion double precision,
    ux double precision,
    jurado_id bigint,
    proyecto_id bigint
);


ALTER TABLE public.jurado_proyectos OWNER TO postgres;

--
-- Name: jurado_proyectos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.jurado_proyectos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jurado_proyectos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mini_talk; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mini_talk (
    id bigint NOT NULL,
    banner character varying(255),
    codigo character varying(255),
    created_at timestamp without time zone,
    descripcion character varying(255),
    fecha timestamp without time zone,
    foto character varying(255),
    grado_academico character varying(255),
    habilitado boolean NOT NULL,
    hora timestamp without time zone,
    institucion character varying(255),
    link_oficial character varying(255),
    nombre character varying(255),
    telefono character varying(255),
    video character varying(255),
    vistas bigint,
    expositor_cod_registro character varying(255),
    gestion_id bigint
);


ALTER TABLE public.mini_talk OWNER TO postgres;

--
-- Name: mini_talk_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mini_talk ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mini_talk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: participante; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.participante (
    id bigint NOT NULL,
    ci character varying(255),
    contacto2 character varying(255),
    contacto3 character varying(255),
    created_at timestamp without time zone,
    descripcion character varying(255),
    foto character varying(255),
    grado_academico character varying(255),
    telefono character varying(255),
    usuario_cod_registro character varying(255)
);


ALTER TABLE public.participante OWNER TO postgres;

--
-- Name: participante_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.participante ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.participante_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: participante_proyecto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.participante_proyecto (
    id bigint NOT NULL,
    create_at timestamp without time zone,
    representante boolean NOT NULL,
    participante_id bigint,
    proyecto_id bigint
);


ALTER TABLE public.participante_proyecto OWNER TO postgres;

--
-- Name: participante_proyecto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.participante_proyecto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.participante_proyecto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proyecto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.proyecto (
    id bigint NOT NULL,
    alcance character varying(255),
    area character varying(255),
    banner character varying(255),
    beneficiarios character varying(255),
    codigo character varying(255),
    create_at timestamp without time zone,
    descripcion character varying(255),
    habilitado boolean NOT NULL,
    link_oficial character varying(255),
    link_video character varying(255),
    nombre character varying(255),
    objetivo_general character varying(255),
    objetivos_especificos character varying(255),
    problematica character varying(255),
    valor_agregado character varying(255),
    vistas bigint,
    equipo_id_equipo bigint,
    gestion_id bigint,
    tipo_proyecto_id bigint
);


ALTER TABLE public.proyecto OWNER TO postgres;

--
-- Name: proyecto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.proyecto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proyecto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rol (
    id_rol bigint NOT NULL,
    tipo character varying(255)
);


ALTER TABLE public.rol OWNER TO postgres;

--
-- Name: rol_id_rol_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rol ALTER COLUMN id_rol ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rol_id_rol_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipo_equipo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_equipo (
    id bigint NOT NULL,
    nombre character varying(255)
);


ALTER TABLE public.tipo_equipo OWNER TO postgres;

--
-- Name: tipo_equipo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_equipo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_equipo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipo_proyecto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_proyecto (
    id bigint NOT NULL,
    nombre character varying(255)
);


ALTER TABLE public.tipo_proyecto OWNER TO postgres;

--
-- Name: tipo_proyecto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_proyecto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_proyecto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    cod_registro character varying(255) NOT NULL,
    correo character varying(255),
    create_at timestamp without time zone,
    habilitado boolean NOT NULL,
    nombre character varying(255),
    password character varying(255),
    sexo character varying(255)
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- Name: usuario_rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario_rol (
    create_at timestamp without time zone,
    usuario_cod_registro character varying(255) NOT NULL,
    rol_id_rol bigint NOT NULL
);


ALTER TABLE public.usuario_rol OWNER TO postgres;

--
-- Data for Name: auspiciador; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auspiciador (id, contacto, create_at, descripcion, link, logo, nombre, gestion_id) FROM stdin;
\.


--
-- Data for Name: equipo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.equipo (id_equipo, create_at, habilitado, nombre, encargado_cod_registro, tipo_equipo_id) FROM stdin;
\.


--
-- Data for Name: gestion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.gestion (id, descripcion, fecha_fin, fecha_ini, gestion, periodo) FROM stdin;
\.


--
-- Data for Name: jurado; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.jurado (id, created_at, grado_academico, telefono, usuario_cod_registro) FROM stdin;
\.


--
-- Data for Name: jurado_proyectos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.jurado_proyectos (id, create_at, funcionalidad, impacto, innovacion, presentacion, ux, jurado_id, proyecto_id) FROM stdin;
\.


--
-- Data for Name: mini_talk; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mini_talk (id, banner, codigo, created_at, descripcion, fecha, foto, grado_academico, habilitado, hora, institucion, link_oficial, nombre, telefono, video, vistas, expositor_cod_registro, gestion_id) FROM stdin;
\.


--
-- Data for Name: participante; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.participante (id, ci, contacto2, contacto3, created_at, descripcion, foto, grado_academico, telefono, usuario_cod_registro) FROM stdin;
\.


--
-- Data for Name: participante_proyecto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.participante_proyecto (id, create_at, representante, participante_id, proyecto_id) FROM stdin;
\.


--
-- Data for Name: proyecto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.proyecto (id, alcance, area, banner, beneficiarios, codigo, create_at, descripcion, habilitado, link_oficial, link_video, nombre, objetivo_general, objetivos_especificos, problematica, valor_agregado, vistas, equipo_id_equipo, gestion_id, tipo_proyecto_id) FROM stdin;
\.


--
-- Data for Name: rol; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rol (id_rol, tipo) FROM stdin;
\.


--
-- Data for Name: tipo_equipo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_equipo (id, nombre) FROM stdin;
\.


--
-- Data for Name: tipo_proyecto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_proyecto (id, nombre) FROM stdin;
\.


--
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (cod_registro, correo, create_at, habilitado, nombre, password, sexo) FROM stdin;
\.


--
-- Data for Name: usuario_rol; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario_rol (create_at, usuario_cod_registro, rol_id_rol) FROM stdin;
\.


--
-- Name: auspiciador_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auspiciador_id_seq', 1, false);


--
-- Name: equipo_id_equipo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.equipo_id_equipo_seq', 1, false);


--
-- Name: gestion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.gestion_id_seq', 1, false);


--
-- Name: jurado_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.jurado_id_seq', 1, false);


--
-- Name: jurado_proyectos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.jurado_proyectos_id_seq', 1, false);


--
-- Name: mini_talk_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mini_talk_id_seq', 1, false);


--
-- Name: participante_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.participante_id_seq', 1, false);


--
-- Name: participante_proyecto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.participante_proyecto_id_seq', 1, false);


--
-- Name: proyecto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.proyecto_id_seq', 1, false);


--
-- Name: rol_id_rol_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rol_id_rol_seq', 1, false);


--
-- Name: tipo_equipo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_equipo_id_seq', 1, false);


--
-- Name: tipo_proyecto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_proyecto_id_seq', 1, false);


--
-- Name: auspiciador auspiciador_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auspiciador
    ADD CONSTRAINT auspiciador_pkey PRIMARY KEY (id);


--
-- Name: equipo equipo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipo
    ADD CONSTRAINT equipo_pkey PRIMARY KEY (id_equipo);


--
-- Name: gestion gestion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gestion
    ADD CONSTRAINT gestion_pkey PRIMARY KEY (id);


--
-- Name: jurado jurado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jurado
    ADD CONSTRAINT jurado_pkey PRIMARY KEY (id);


--
-- Name: jurado_proyectos jurado_proyectos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jurado_proyectos
    ADD CONSTRAINT jurado_proyectos_pkey PRIMARY KEY (id);


--
-- Name: mini_talk mini_talk_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mini_talk
    ADD CONSTRAINT mini_talk_pkey PRIMARY KEY (id);


--
-- Name: participante participante_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.participante
    ADD CONSTRAINT participante_pkey PRIMARY KEY (id);


--
-- Name: participante_proyecto participante_proyecto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.participante_proyecto
    ADD CONSTRAINT participante_proyecto_pkey PRIMARY KEY (id);


--
-- Name: proyecto proyecto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proyecto
    ADD CONSTRAINT proyecto_pkey PRIMARY KEY (id);


--
-- Name: rol rol_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (id_rol);


--
-- Name: tipo_equipo tipo_equipo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_equipo
    ADD CONSTRAINT tipo_equipo_pkey PRIMARY KEY (id);


--
-- Name: tipo_proyecto tipo_proyecto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_proyecto
    ADD CONSTRAINT tipo_proyecto_pkey PRIMARY KEY (id);


--
-- Name: usuario uk_2mlfr087gb1ce55f2j87o74t; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk_2mlfr087gb1ce55f2j87o74t UNIQUE (correo);


--
-- Name: usuario uk_cto7dkti4t38iq8r4cqesbd8k; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk_cto7dkti4t38iq8r4cqesbd8k UNIQUE (nombre);


--
-- Name: mini_talk uk_tirovnbpa6f448g4gkblvhus7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mini_talk
    ADD CONSTRAINT uk_tirovnbpa6f448g4gkblvhus7 UNIQUE (nombre);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (cod_registro);


--
-- Name: usuario_rol usuario_rol_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_rol
    ADD CONSTRAINT usuario_rol_pkey PRIMARY KEY (usuario_cod_registro, rol_id_rol);


--
-- Name: usuario_rol fk238u3ay4oc5keejnx21k7779t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_rol
    ADD CONSTRAINT fk238u3ay4oc5keejnx21k7779t FOREIGN KEY (usuario_cod_registro) REFERENCES public.usuario(cod_registro);


--
-- Name: proyecto fk40s9wwelokk6yfb0ycd702e0q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proyecto
    ADD CONSTRAINT fk40s9wwelokk6yfb0ycd702e0q FOREIGN KEY (gestion_id) REFERENCES public.gestion(id);


--
-- Name: usuario_rol fk5liaxc45dw4i8bxmcjgjn1wrk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_rol
    ADD CONSTRAINT fk5liaxc45dw4i8bxmcjgjn1wrk FOREIGN KEY (rol_id_rol) REFERENCES public.rol(id_rol);


--
-- Name: jurado_proyectos fk6rrthlqve5y6cvhingmsm67u9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jurado_proyectos
    ADD CONSTRAINT fk6rrthlqve5y6cvhingmsm67u9 FOREIGN KEY (proyecto_id) REFERENCES public.proyecto(id);


--
-- Name: participante_proyecto fk710tcirhwvb1pqin2foornvwu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.participante_proyecto
    ADD CONSTRAINT fk710tcirhwvb1pqin2foornvwu FOREIGN KEY (proyecto_id) REFERENCES public.proyecto(id);


--
-- Name: mini_talk fk8lcx10cta11rrrl3gjybvptd9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mini_talk
    ADD CONSTRAINT fk8lcx10cta11rrrl3gjybvptd9 FOREIGN KEY (expositor_cod_registro) REFERENCES public.usuario(cod_registro);


--
-- Name: equipo fken8egoe4ykcssr6563qqxe6hd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipo
    ADD CONSTRAINT fken8egoe4ykcssr6563qqxe6hd FOREIGN KEY (encargado_cod_registro) REFERENCES public.usuario(cod_registro);


--
-- Name: participante_proyecto fkf8767wtbxh1j8uof1di7d49op; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.participante_proyecto
    ADD CONSTRAINT fkf8767wtbxh1j8uof1di7d49op FOREIGN KEY (participante_id) REFERENCES public.participante(id);


--
-- Name: participante fkgrq4rqynkxlqexeftf1fraewr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.participante
    ADD CONSTRAINT fkgrq4rqynkxlqexeftf1fraewr FOREIGN KEY (usuario_cod_registro) REFERENCES public.usuario(cod_registro);


--
-- Name: jurado_proyectos fkii0aoj6ek354fk2tvqjcqowal; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jurado_proyectos
    ADD CONSTRAINT fkii0aoj6ek354fk2tvqjcqowal FOREIGN KEY (jurado_id) REFERENCES public.jurado(id);


--
-- Name: proyecto fkl1uyjgkvnaouxao3gelk4m560; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proyecto
    ADD CONSTRAINT fkl1uyjgkvnaouxao3gelk4m560 FOREIGN KEY (tipo_proyecto_id) REFERENCES public.tipo_proyecto(id);


--
-- Name: jurado fkllstcarri6kw8nkflqy6n1hsw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jurado
    ADD CONSTRAINT fkllstcarri6kw8nkflqy6n1hsw FOREIGN KEY (usuario_cod_registro) REFERENCES public.usuario(cod_registro);


--
-- Name: proyecto fkmeaxlelntp9di9dyw92x634ds; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proyecto
    ADD CONSTRAINT fkmeaxlelntp9di9dyw92x634ds FOREIGN KEY (equipo_id_equipo) REFERENCES public.equipo(id_equipo);


--
-- Name: auspiciador fkno61r413gtbrslgb0bsinpfex; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auspiciador
    ADD CONSTRAINT fkno61r413gtbrslgb0bsinpfex FOREIGN KEY (gestion_id) REFERENCES public.gestion(id);


--
-- Name: equipo fktdseewpyhkudv1ft4hgrbbwtv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipo
    ADD CONSTRAINT fktdseewpyhkudv1ft4hgrbbwtv FOREIGN KEY (tipo_equipo_id) REFERENCES public.tipo_equipo(id);


--
-- Name: mini_talk fktlqldv4yi2sx3j5xt5wol6j7l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mini_talk
    ADD CONSTRAINT fktlqldv4yi2sx3j5xt5wol6j7l FOREIGN KEY (gestion_id) REFERENCES public.gestion(id);

--
-- PostgreSQL database dump complete
--

